opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- empty_count
- empty_string
- explicit_init
- fallthrough
- file_header
- file_name_no_space
- first_where
- force_unwrapping
- implicitly_unwrapped_optional
- joined_default_parameter
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- operator_usage_whitespace
- overridden_super_call
- redundant_nil_coalescing
- redundant_type_annotation
- shorthand_optional_binding
- sorted_first_last
- switch_case_on_newline
- toggle_bool
- unneeded_parentheses_in_closure_argument
- vertical_whitespace_closing_braces
- yoda_condition

disabled_rules:
- trailing_whitespace
- multiple_closures_with_trailing_closure

attributes:
  always_on_same_line:
  - '@objc'
  - '@NSApplicationDelegateAdaptor'
  - '@Environment'

identifier_name:
  excluded:
  - id

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

excluded: 
 - Carthage
 - Pods

custom_rules:
  comments_space:
    name: "Space after comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
  double_space:
    name: "Double space"
    regex: '([a-z,A-Z] \s+)'
    message: "Don't use double space between keywords"
    match_kinds: keyword
    severity: warning
  empty_commented_line:
    name: "Empty commented out line"
    regex: '(\t+| +)//\n'
    message: "Remove useless comment lines or use /* format */"
    severity: warning
